### ISSUE TITLE
Add help text when running without any params

### ISSUE THREAD

**Issue by miynat** [recepkizilarslan/Piling#1]
When the Piling binary is called without any parameters it throws an **ArgumentNullException**:

![image](https://user-images.githubusercontent.com/1431760/140440709-448b468a-4c4b-465d-a513-1f2f66fa4f8b.png)

> scan param is required
> Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
>    at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
>    at System.Text.RegularExpressions.Regex.IsMatch(String input)
>    at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
>    at Piling.Helper.ParameterValidator.IsValidIP(String ipAddress) in /home/selcuk/tutorials/Piling/Piling/Helper/ParameterValidator.cs:line 25
>    at Piling.Helper.ParameterHandler.Handle(String[] args) in /home/selcuk/tutorials/Piling/Piling/Helper/ParameterHandler.cs:line 28
>    at Piling.Program.Main(String[] args) in /home/selcuk/tutorials/Piling/Piling/Program.cs:line 37
> [1]    17863 abort      ./Piling

Instead of throwing an exception, it would be better to output a help text about usage of the program.

(Also, adding a new parameter named **help** could be more user-friendly)

**Comment by recepkizilarslan** [comment]
Yes that would be great. Thanks for the feedback

**Comment by recepkizilarslan** [comment]
Done thx for your feedback
