### ISSUE TITLE
[Feature Request] Add support for using domain names instead of IP addresses

### ISSUE THREAD

**Issue by miynat** [recepkizilarslan/Piling#2]
It would be helpful having a chance to use domain name instead of IP address could be a useful addition, like:

./Piling scan google.com.tr from 12 to 65535 then save out.txt

![image](https://user-images.githubusercontent.com/1431760/140440994-a01bbd97-0fbb-4bee-8138-5089b629bb4e.png)

> 
> Unhandled exception. System.FormatException: Unknown IP range string.
>    at NetTools.IPAddressRange.Parse(String ipRangeString)
>    at Piling.ScanManager.<Start>b__9_0() in /home/selcuk/tutorials/Piling/Piling/ScanManager.cs:line 90
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> [1]    17876 abort      ./Piling scan google.com.tr from 12 to 65535 then save out.txt

**Comment by recepkizilarslan** [comment]
Done.
Thx for your good feedback
